server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 表示是否将自己注册进eureka
    register-with-eureka: true
    # 是否从Eureka 服务中抓取已有的注册信息，默认为True，集群下必须设置true配合ribbon 负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
            defaultZone: http://localhost:7001/eureka

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.sc.springcloud.service.PaymentFeignService: debug